In [2]:
!pip install nbimporter

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3.9 -m pip install --upgrade pip


In [46]:
import numpy as np
import nbimporter
from pymatgen.ext.matproj import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [47]:
mp_key = "n522DVkKQfm3sukNMEVKlnOE5jidGbIJ"
mp_id = "mp-2530"

In [48]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [49]:
view = quick_view(conv_struc, "packed", conventional = True)
display(view)
view.script('rotate on')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

# Structure symmetry

In [64]:
## Li
i_atom = 1
i_symmop = 50

view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [59]:
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0.5 0.5 0. ]


In [60]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.75 0.25 0.75]


In [61]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[-0.25  0.25 -0.75]


In [62]:
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print(j_atom, conv_struc.sites[j_atom -1].frac_coords)

8 [0.75 0.25 0.25]


In [63]:
view2 = quick_view(conv_struc, "packed", conventional = True)
display(view2)


view2.script('draw SYMOP ' + str(i_symmop + 1) + ' {atomno = ' + str(i_atom) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

## 2e élément

In [85]:
i_atom = 2
i_symmop = 100

view2 = quick_view(prim_struc, "packed", conventional = True)
display(view2)
view2.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [80]:
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0.5 0.  0.5]


In [81]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.25 0.75 0.25]


In [82]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[ 1.25 -0.25  0.25]


In [83]:
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print(j_atom, conv_struc.sites[j_atom -1].frac_coords)

2 [0.25 0.75 0.25]


In [87]:
#view2 = quick_view(conv_struc, "packed", conventional = True)
#display(view2)


#view2.script('draw SYMOP ' + str(i_symmop + 1) + ' {atomno = ' + str(i_atom) + '}')

## 3e élément

In [78]:
i_atom = 12
i_symmop = 153

In [73]:
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0.  0.5 0.5]


In [74]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.5 0.5 0. ]


In [75]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[0.5 0.  0.5]


In [76]:
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print(j_atom, conv_struc.sites[j_atom -1].frac_coords)

11 [0.5 0.  0.5]


In [77]:
view2 = quick_view(conv_struc, "packed", conventional = True)
display(view2)


view2.script('draw SYMOP ' + str(i_symmop + 1) + ' {atomno = ' + str(i_atom) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))